name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      name: Set up JDK 17
      with:
        java-version: 17
        distribution: adopt-hotspot
    - name: Build L-System.js
      run: |
        chmod +x gradlew
        ./gradlew build check
